# Rust toolchain configuration file

# Specify the default toolchain to use
# This can be overridden by the `rustup override` command
# or by setting the `RUSTUP_TOOLCHAIN` environment variable
# to a different toolchain name.
# https://github.com/rust-lang/rust/blob/master/RELEASES.md

[toolchain]
channel = "1.74.1"