//! All symbols that are used by CodeParser

#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use crate::symbol::Symbol;

// NOTE: // Symbols are fully qualified using "<context>`<symbolname>" instead of just
// "<symbolname>".
//
// We want to fully-qualify symbol names over the wire.
// This allows library->kernel traffic to work when CodeParser` is not on $ContextPath.
// However, it is still not possible to fully-qualify System` symbols
// Related bugs: 283291, 284492
// So also make library->kernel traffic match this behavior

//======================================
// Symbols
//======================================

crate::symbol::symbol! {
    All;
    Degree;
    Pi;
    Infinity;
    E;
    I;

    Information;

    Before;
    After;

    Inequality;

    Equal;
    Unequal;
    Less;
    Greater;
    LessEqual;
    GreaterEqual;
    GreaterEqualLess;
    GreaterFullEqual;
    GreaterGreater;
    GreaterLess;
    GreaterSlantEqual;
    LessSlantEqual;
    //
    // GreaterSlantEqual parses to GreaterEqual
    // Related bugs: 78439
    //
    GreaterTilde;
    LessEqualGreater;
    LessFullEqual;
    LessGreater;
    LessLess;
    //
    // LessSlantEqual parses to LessEqual
    // Related bugs: 78439
    //
    LessTilde;
    NestedGreaterGreater;
    NestedLessLess;
    NotGreater;
    NotGreaterEqual;
    NotGreaterFullEqual;
    NotGreaterGreater;
    NotGreaterLess;
    NotGreaterSlantEqual;
    NotGreaterTilde;
    NotLess;
    NotLessEqual;
    NotLessFullEqual;
    NotLessGreater;
    NotLessLess;
    NotLessSlantEqual;
    NotLessTilde;
    NotNestedGreaterGreater;
    NotNestedLessLess;
}

crate::symbol::nested_symbol! {
    Developer::{
        VectorInequality
    }
}

crate::symbol::nested_symbol! {
    CodeParser::{
        Comment
    }
}

pub const CodeParser_AbstractSyntaxErrorNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`AbstractSyntaxErrorNode") };
pub const CodeParser_BinaryAt: Symbol = unsafe { Symbol::unchecked_new("CodeParser`BinaryAt") };
pub const CodeParser_BinaryNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`BinaryNode") };
pub const CodeParser_BinarySlashSlash: Symbol = unsafe { Symbol::unchecked_new("CodeParser`BinarySlashSlash") };
pub const CodeParser_BoxNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`BoxNode") };
pub const CodeParser_CallMissingCloserNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CallMissingCloserNode") };
pub const CodeParser_CallNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CallNode") };
pub const CodeParser_CodeAction: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CodeAction") };
pub const CodeParser_CodeActions: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CodeActions") };
pub const CodeParser_CodeNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CodeNode") };
pub const CodeParser_Comma: Symbol = unsafe { Symbol::unchecked_new("CodeParser`Comma") };
pub const CodeParser_CompoundNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`CompoundNode") };
pub const CodeParser_ContainerNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`ContainerNode") };
pub const CodeParser_DeleteText: Symbol = unsafe { Symbol::unchecked_new("CodeParser`DeleteText") };
pub const CodeParser_EncodingIssue: Symbol = unsafe { Symbol::unchecked_new("CodeParser`EncodingIssue") };
pub const CodeParser_ErrorNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`ErrorNode") };
pub const CodeParser_FormatIssue: Symbol = unsafe { Symbol::unchecked_new("CodeParser`FormatIssue") };
pub const CodeParser_GroupDoubleBracket: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupDoubleBracket") };
pub const CodeParser_GroupMissingCloserNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupMissingCloserNode") };
pub const CodeParser_GroupMissingOpenerNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupMissingOpenerNode") };
pub const CodeParser_GroupNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupNode") };
pub const CodeParser_GroupParen: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupParen") };
pub const CodeParser_GroupSquare: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupSquare") };
pub const CodeParser_GroupTypeSpecifier: Symbol = unsafe { Symbol::unchecked_new("CodeParser`GroupTypeSpecifier") };
pub const CodeParser_InfixInequality: Symbol = unsafe { Symbol::unchecked_new("CodeParser`InfixInequality") };
pub const CodeParser_InfixNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`InfixNode") };
pub const CodeParser_InfixTilde: Symbol = unsafe { Symbol::unchecked_new("CodeParser`InfixTilde") };
pub const CodeParser_InsertText: Symbol = unsafe { Symbol::unchecked_new("CodeParser`InsertText") };
pub const CodeParser_InternalInvalid: Symbol = unsafe { Symbol::unchecked_new("CodeParser`InternalInvalid") };
pub const CodeParser_LeafNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`LeafNode") };
pub const CodeParser_Library_LongNameSuggestion: Symbol = unsafe { Symbol::unchecked_new("CodeParser`Library`LongNameSuggestion") };
pub const CodeParser_Library_SetConcreteParseProgress: Symbol = unsafe { Symbol::unchecked_new("CodeParser`Library`SetConcreteParseProgress") };
pub const CodeParser_PatternBlank: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PatternBlank") };
pub const CodeParser_PatternBlankNullSequence: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PatternBlankNullSequence") };
pub const CodeParser_PatternBlankSequence: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PatternBlankSequence") };
pub const CodeParser_PatternOptionalDefault: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PatternOptionalDefault") };
pub const CodeParser_PostfixNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PostfixNode") };
pub const CodeParser_PrefixBinaryNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PrefixBinaryNode") };
pub const CodeParser_PrefixLinearSyntaxBang: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PrefixLinearSyntaxBang") };
pub const CodeParser_PrefixNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PrefixNode") };
pub const CodeParser_PrefixNot2: Symbol = unsafe { Symbol::unchecked_new("CodeParser`PrefixNot2") };
pub const CodeParser_ReplaceText: Symbol = unsafe { Symbol::unchecked_new("CodeParser`ReplaceText") };
pub const CodeParser_Source: Symbol = unsafe { Symbol::unchecked_new("CodeParser`Source") };
pub const CodeParser_SyntaxErrorNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`SyntaxErrorNode") };
pub const CodeParser_SyntaxIssue: Symbol = unsafe { Symbol::unchecked_new("CodeParser`SyntaxIssue") };
pub const CodeParser_TernaryNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`TernaryNode") };
pub const CodeParser_TernaryOptionalPattern: Symbol = unsafe { Symbol::unchecked_new("CodeParser`TernaryOptionalPattern") };
pub const CodeParser_TernaryTilde: Symbol = unsafe { Symbol::unchecked_new("CodeParser`TernaryTilde") };
pub const CodeParser_UnterminatedTokenErrorNeedsReparseNode: Symbol = unsafe { Symbol::unchecked_new("CodeParser`UnterminatedTokenErrorNeedsReparseNode") };
pub const SyntaxError_ExpectedSet: Symbol = unsafe { Symbol::unchecked_new("SyntaxError`ExpectedSet") };
pub const SyntaxError_ExpectedSymbol: Symbol = unsafe { Symbol::unchecked_new("SyntaxError`ExpectedSymbol") };
pub const SyntaxError_ExpectedTilde: Symbol = unsafe { Symbol::unchecked_new("SyntaxError`ExpectedTilde") };
pub const AddTo: Symbol = unsafe { Symbol::unchecked_new("System`AddTo") };
pub const Alternatives: Symbol = unsafe { Symbol::unchecked_new("System`Alternatives") };
pub const And: Symbol = unsafe { Symbol::unchecked_new("System`And") };
pub const AngleBracket: Symbol = unsafe { Symbol::unchecked_new("System`AngleBracket") };
pub const Application: Symbol = unsafe { Symbol::unchecked_new("System`Application") };
pub const Apply: Symbol = unsafe { Symbol::unchecked_new("System`Apply") };
pub const ApplyTo: Symbol = unsafe { Symbol::unchecked_new("System`ApplyTo") };
pub const Association: Symbol = unsafe { Symbol::unchecked_new("System`Association") };
pub const Backslash: Symbol = unsafe { Symbol::unchecked_new("System`Backslash") };
pub const Because: Symbol = unsafe { Symbol::unchecked_new("System`Because") };
pub const Blank: Symbol = unsafe { Symbol::unchecked_new("System`Blank") };
pub const BlankNullSequence: Symbol = unsafe { Symbol::unchecked_new("System`BlankNullSequence") };
pub const BlankSequence: Symbol = unsafe { Symbol::unchecked_new("System`BlankSequence") };
pub const BracketingBar: Symbol = unsafe { Symbol::unchecked_new("System`BracketingBar") };
pub const ByteArray: Symbol = unsafe { Symbol::unchecked_new("System`ByteArray") };
pub const Cap: Symbol = unsafe { Symbol::unchecked_new("System`Cap") };
pub const CapitalDifferentialD: Symbol = unsafe { Symbol::unchecked_new("System`CapitalDifferentialD") };
pub const Ceiling: Symbol = unsafe { Symbol::unchecked_new("System`Ceiling") };
pub const CenterDot: Symbol = unsafe { Symbol::unchecked_new("System`CenterDot") };
pub const CircleDot: Symbol = unsafe { Symbol::unchecked_new("System`CircleDot") };
pub const CircleMinus: Symbol = unsafe { Symbol::unchecked_new("System`CircleMinus") };
pub const CirclePlus: Symbol = unsafe { Symbol::unchecked_new("System`CirclePlus") };
pub const CircleTimes: Symbol = unsafe { Symbol::unchecked_new("System`CircleTimes") };
pub const ClockwiseContourIntegral: Symbol = unsafe { Symbol::unchecked_new("System`ClockwiseContourIntegral") };
pub const Colon: Symbol = unsafe { Symbol::unchecked_new("System`Colon") };
pub const Composition: Symbol = unsafe { Symbol::unchecked_new("System`Composition") };
pub const CompoundExpression: Symbol = unsafe { Symbol::unchecked_new("System`CompoundExpression") };
pub const Condition: Symbol = unsafe { Symbol::unchecked_new("System`Condition") };
pub const Conditioned: Symbol = unsafe { Symbol::unchecked_new("System`Conditioned") };
pub const ConfidenceLevel: Symbol = unsafe { Symbol::unchecked_new("System`ConfidenceLevel") };
pub const Congruent: Symbol = unsafe { Symbol::unchecked_new("System`Congruent") };
pub const Conjugate: Symbol = unsafe { Symbol::unchecked_new("System`Conjugate") };
pub const ConjugateTranspose: Symbol = unsafe { Symbol::unchecked_new("System`ConjugateTranspose") };
pub const ContinuedFractionK: Symbol = unsafe { Symbol::unchecked_new("System`ContinuedFractionK") };
pub const ContourIntegral: Symbol = unsafe { Symbol::unchecked_new("System`ContourIntegral") };
pub const Coproduct: Symbol = unsafe { Symbol::unchecked_new("System`Coproduct") };
pub const CounterClockwiseContourIntegral: Symbol = unsafe { Symbol::unchecked_new("System`CounterClockwiseContourIntegral") };
pub const Cross: Symbol = unsafe { Symbol::unchecked_new("System`Cross") };
pub const CubeRoot: Symbol = unsafe { Symbol::unchecked_new("System`CubeRoot") };
pub const Cup: Symbol = unsafe { Symbol::unchecked_new("System`Cup") };
pub const CupCap: Symbol = unsafe { Symbol::unchecked_new("System`CupCap") };
pub const CurlyDoubleQuote: Symbol = unsafe { Symbol::unchecked_new("System`CurlyDoubleQuote") };
pub const CurlyQuote: Symbol = unsafe { Symbol::unchecked_new("System`CurlyQuote") };
pub const Decrement: Symbol = unsafe { Symbol::unchecked_new("System`Decrement") };
pub const Del: Symbol = unsafe { Symbol::unchecked_new("System`Del") };
pub const Derivative: Symbol = unsafe { Symbol::unchecked_new("System`Derivative") };
pub const Diamond: Symbol = unsafe { Symbol::unchecked_new("System`Diamond") };
pub const DifferentialD: Symbol = unsafe { Symbol::unchecked_new("System`DifferentialD") };
pub const DirectedEdge: Symbol = unsafe { Symbol::unchecked_new("System`DirectedEdge") };
pub const Distributed: Symbol = unsafe { Symbol::unchecked_new("System`Distributed") };
pub const Divide: Symbol = unsafe { Symbol::unchecked_new("System`Divide") };
pub const DivideBy: Symbol = unsafe { Symbol::unchecked_new("System`DivideBy") };
pub const Divisible: Symbol = unsafe { Symbol::unchecked_new("System`Divisible") };
pub const Dot: Symbol = unsafe { Symbol::unchecked_new("System`Dot") };
pub const DotEqual: Symbol = unsafe { Symbol::unchecked_new("System`DotEqual") };
pub const DoubleBracketingBar: Symbol = unsafe { Symbol::unchecked_new("System`DoubleBracketingBar") };
pub const DoubleContourIntegral: Symbol = unsafe { Symbol::unchecked_new("System`DoubleContourIntegral") };
pub const DoubleDownArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleDownArrow") };
pub const DoubleLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLeftArrow") };
pub const DoubleLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLeftRightArrow") };
pub const DoubleLeftTee: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLeftTee") };
pub const DoubleLongLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLongLeftArrow") };
pub const DoubleLongLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLongLeftRightArrow") };
pub const DoubleLongRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleLongRightArrow") };
pub const DoubleRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleRightArrow") };
pub const DoubleRightTee: Symbol = unsafe { Symbol::unchecked_new("System`DoubleRightTee") };
pub const DoubleUpArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleUpArrow") };
pub const DoubleUpDownArrow: Symbol = unsafe { Symbol::unchecked_new("System`DoubleUpDownArrow") };
pub const DoubleVerticalBar: Symbol = unsafe { Symbol::unchecked_new("System`DoubleVerticalBar") };
pub const DownArrow: Symbol = unsafe { Symbol::unchecked_new("System`DownArrow") };
pub const DownArrowBar: Symbol = unsafe { Symbol::unchecked_new("System`DownArrowBar") };
pub const DownArrowUpArrow: Symbol = unsafe { Symbol::unchecked_new("System`DownArrowUpArrow") };
pub const DownLeftRightVector: Symbol = unsafe { Symbol::unchecked_new("System`DownLeftRightVector") };
pub const DownLeftTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`DownLeftTeeVector") };
pub const DownLeftVector: Symbol = unsafe { Symbol::unchecked_new("System`DownLeftVector") };
pub const DownLeftVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`DownLeftVectorBar") };
pub const DownRightTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`DownRightTeeVector") };
pub const DownRightVector: Symbol = unsafe { Symbol::unchecked_new("System`DownRightVector") };
pub const DownRightVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`DownRightVectorBar") };
pub const DownTee: Symbol = unsafe { Symbol::unchecked_new("System`DownTee") };
pub const DownTeeArrow: Symbol = unsafe { Symbol::unchecked_new("System`DownTeeArrow") };
pub const Element: Symbol = unsafe { Symbol::unchecked_new("System`Element") };
pub const EndOfFile: Symbol = unsafe { Symbol::unchecked_new("System`EndOfFile") };
pub const EqualTilde: Symbol = unsafe { Symbol::unchecked_new("System`EqualTilde") };
pub const Equilibrium: Symbol = unsafe { Symbol::unchecked_new("System`Equilibrium") };
pub const Equivalent: Symbol = unsafe { Symbol::unchecked_new("System`Equivalent") };
pub const EvaluatePacket: Symbol = unsafe { Symbol::unchecked_new("System`EvaluatePacket") };
pub const Exists: Symbol = unsafe { Symbol::unchecked_new("System`Exists") };
pub const ExpectationE: Symbol = unsafe { Symbol::unchecked_new("System`ExpectationE") };
pub const Factorial: Symbol = unsafe { Symbol::unchecked_new("System`Factorial") };
pub const Factorial2: Symbol = unsafe { Symbol::unchecked_new("System`Factorial2") };
pub const Floor: Symbol = unsafe { Symbol::unchecked_new("System`Floor") };
pub const ForAll: Symbol = unsafe { Symbol::unchecked_new("System`ForAll") };
pub const Function: Symbol = unsafe { Symbol::unchecked_new("System`Function") };
pub const Get: Symbol = unsafe { Symbol::unchecked_new("System`Get") };
pub const HermitianConjugate: Symbol = unsafe { Symbol::unchecked_new("System`HermitianConjugate") };
pub const HumpDownHump: Symbol = unsafe { Symbol::unchecked_new("System`HumpDownHump") };
pub const HumpEqual: Symbol = unsafe { Symbol::unchecked_new("System`HumpEqual") };
pub const Implies: Symbol = unsafe { Symbol::unchecked_new("System`Implies") };
pub const Increment: Symbol = unsafe { Symbol::unchecked_new("System`Increment") };
pub const Integer: Symbol = unsafe { Symbol::unchecked_new("System`Integer") };
pub const Integral: Symbol = unsafe { Symbol::unchecked_new("System`Integral") };
pub const Integrate: Symbol = unsafe { Symbol::unchecked_new("System`Integrate") };
pub const Intersection: Symbol = unsafe { Symbol::unchecked_new("System`Intersection") };
pub const InvisiblePostfixScriptBase: Symbol = unsafe { Symbol::unchecked_new("System`InvisiblePostfixScriptBase") };
pub const InvisiblePrefixScriptBase: Symbol = unsafe { Symbol::unchecked_new("System`InvisiblePrefixScriptBase") };
pub const LeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`LeftArrow") };
pub const LeftArrowBar: Symbol = unsafe { Symbol::unchecked_new("System`LeftArrowBar") };
pub const LeftArrowRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`LeftArrowRightArrow") };
pub const LeftDownTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftDownTeeVector") };
pub const LeftDownVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftDownVector") };
pub const LeftDownVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`LeftDownVectorBar") };
pub const LeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`LeftRightArrow") };
pub const LeftRightVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftRightVector") };
pub const LeftTee: Symbol = unsafe { Symbol::unchecked_new("System`LeftTee") };
pub const LeftTeeArrow: Symbol = unsafe { Symbol::unchecked_new("System`LeftTeeArrow") };
pub const LeftTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftTeeVector") };
pub const LeftTriangle: Symbol = unsafe { Symbol::unchecked_new("System`LeftTriangle") };
pub const LeftTriangleBar: Symbol = unsafe { Symbol::unchecked_new("System`LeftTriangleBar") };
pub const LeftTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("System`LeftTriangleEqual") };
pub const LeftUpDownVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftUpDownVector") };
pub const LeftUpTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftUpTeeVector") };
pub const LeftUpVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftUpVector") };
pub const LeftUpVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`LeftUpVectorBar") };
pub const LeftVector: Symbol = unsafe { Symbol::unchecked_new("System`LeftVector") };
pub const LeftVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`LeftVectorBar") };
pub const List: Symbol = unsafe { Symbol::unchecked_new("System`List") };
pub const LongLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`LongLeftArrow") };
pub const LongLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`LongLeftRightArrow") };
pub const LongRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`LongRightArrow") };
pub const LowerLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`LowerLeftArrow") };
pub const LowerRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`LowerRightArrow") };
pub const Map: Symbol = unsafe { Symbol::unchecked_new("System`Map") };
pub const MapAll: Symbol = unsafe { Symbol::unchecked_new("System`MapAll") };
pub const MapApply: Symbol = unsafe { Symbol::unchecked_new("System`MapApply") };
pub const MessageName: Symbol = unsafe { Symbol::unchecked_new("System`MessageName") };
pub const Minus: Symbol = unsafe { Symbol::unchecked_new("System`Minus") };
pub const MinusPlus: Symbol = unsafe { Symbol::unchecked_new("System`MinusPlus") };
pub const Missing: Symbol = unsafe { Symbol::unchecked_new("System`Missing") };
pub const Nand: Symbol = unsafe { Symbol::unchecked_new("System`Nand") };
pub const NonCommutativeMultiply: Symbol = unsafe { Symbol::unchecked_new("System`NonCommutativeMultiply") };
pub const Nor: Symbol = unsafe { Symbol::unchecked_new("System`Nor") };
pub const Not: Symbol = unsafe { Symbol::unchecked_new("System`Not") };
pub const NotCongruent: Symbol = unsafe { Symbol::unchecked_new("System`NotCongruent") };
pub const NotCupCap: Symbol = unsafe { Symbol::unchecked_new("System`NotCupCap") };
pub const NotDoubleVerticalBar: Symbol = unsafe { Symbol::unchecked_new("System`NotDoubleVerticalBar") };
pub const NotElement: Symbol = unsafe { Symbol::unchecked_new("System`NotElement") };
pub const NotEqualTilde: Symbol = unsafe { Symbol::unchecked_new("System`NotEqualTilde") };
pub const NotExists: Symbol = unsafe { Symbol::unchecked_new("System`NotExists") };
pub const Nothing: Symbol = unsafe { Symbol::unchecked_new("System`Nothing") };
pub const NotHumpDownHump: Symbol = unsafe { Symbol::unchecked_new("System`NotHumpDownHump") };
pub const NotHumpEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotHumpEqual") };
pub const NotLeftTriangle: Symbol = unsafe { Symbol::unchecked_new("System`NotLeftTriangle") };
pub const NotLeftTriangleBar: Symbol = unsafe { Symbol::unchecked_new("System`NotLeftTriangleBar") };
pub const NotLeftTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotLeftTriangleEqual") };
pub const NotPrecedes: Symbol = unsafe { Symbol::unchecked_new("System`NotPrecedes") };
pub const NotPrecedesEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotPrecedesEqual") };
pub const NotPrecedesSlantEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotPrecedesSlantEqual") };
pub const NotPrecedesTilde: Symbol = unsafe { Symbol::unchecked_new("System`NotPrecedesTilde") };
pub const NotReverseElement: Symbol = unsafe { Symbol::unchecked_new("System`NotReverseElement") };
pub const NotRightTriangle: Symbol = unsafe { Symbol::unchecked_new("System`NotRightTriangle") };
pub const NotRightTriangleBar: Symbol = unsafe { Symbol::unchecked_new("System`NotRightTriangleBar") };
pub const NotRightTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotRightTriangleEqual") };
pub const NotSquareSubset: Symbol = unsafe { Symbol::unchecked_new("System`NotSquareSubset") };
pub const NotSquareSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSquareSubsetEqual") };
pub const NotSquareSuperset: Symbol = unsafe { Symbol::unchecked_new("System`NotSquareSuperset") };
pub const NotSquareSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSquareSupersetEqual") };
pub const NotSubset: Symbol = unsafe { Symbol::unchecked_new("System`NotSubset") };
pub const NotSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSubsetEqual") };
pub const NotSucceeds: Symbol = unsafe { Symbol::unchecked_new("System`NotSucceeds") };
pub const NotSucceedsEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSucceedsEqual") };
pub const NotSucceedsSlantEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSucceedsSlantEqual") };
pub const NotSucceedsTilde: Symbol = unsafe { Symbol::unchecked_new("System`NotSucceedsTilde") };
pub const NotSuperset: Symbol = unsafe { Symbol::unchecked_new("System`NotSuperset") };
pub const NotSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotSupersetEqual") };
pub const NotTilde: Symbol = unsafe { Symbol::unchecked_new("System`NotTilde") };
pub const NotTildeEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotTildeEqual") };
pub const NotTildeFullEqual: Symbol = unsafe { Symbol::unchecked_new("System`NotTildeFullEqual") };
pub const NotTildeTilde: Symbol = unsafe { Symbol::unchecked_new("System`NotTildeTilde") };
pub const NotVerticalBar: Symbol = unsafe { Symbol::unchecked_new("System`NotVerticalBar") };
pub const Null: Symbol = unsafe { Symbol::unchecked_new("System`Null") };
pub const Optional: Symbol = unsafe { Symbol::unchecked_new("System`Optional") };
pub const Or: Symbol = unsafe { Symbol::unchecked_new("System`Or") };
pub const Out: Symbol = unsafe { Symbol::unchecked_new("System`Out") };
pub const Part: Symbol = unsafe { Symbol::unchecked_new("System`Part") };
pub const Pattern: Symbol = unsafe { Symbol::unchecked_new("System`Pattern") };
pub const PatternTest: Symbol = unsafe { Symbol::unchecked_new("System`PatternTest") };
pub const PermutationProduct: Symbol = unsafe { Symbol::unchecked_new("System`PermutationProduct") };
pub const Perpendicular: Symbol = unsafe { Symbol::unchecked_new("System`Perpendicular") };
pub const Piecewise: Symbol = unsafe { Symbol::unchecked_new("System`Piecewise") };
pub const Plus: Symbol = unsafe { Symbol::unchecked_new("System`Plus") };
pub const PlusMinus: Symbol = unsafe { Symbol::unchecked_new("System`PlusMinus") };
pub const Power: Symbol = unsafe { Symbol::unchecked_new("System`Power") };
pub const Precedes: Symbol = unsafe { Symbol::unchecked_new("System`Precedes") };
pub const PrecedesEqual: Symbol = unsafe { Symbol::unchecked_new("System`PrecedesEqual") };
pub const PrecedesSlantEqual: Symbol = unsafe { Symbol::unchecked_new("System`PrecedesSlantEqual") };
pub const PrecedesTilde: Symbol = unsafe { Symbol::unchecked_new("System`PrecedesTilde") };
pub const PreDecrement: Symbol = unsafe { Symbol::unchecked_new("System`PreDecrement") };
pub const PreIncrement: Symbol = unsafe { Symbol::unchecked_new("System`PreIncrement") };
pub const ProbabilityPr: Symbol = unsafe { Symbol::unchecked_new("System`ProbabilityPr") };
pub const Product: Symbol = unsafe { Symbol::unchecked_new("System`Product") };
pub const Proportion: Symbol = unsafe { Symbol::unchecked_new("System`Proportion") };
pub const Proportional: Symbol = unsafe { Symbol::unchecked_new("System`Proportional") };
pub const Put: Symbol = unsafe { Symbol::unchecked_new("System`Put") };
pub const PutAppend: Symbol = unsafe { Symbol::unchecked_new("System`PutAppend") };
pub const Rational: Symbol = unsafe { Symbol::unchecked_new("System`Rational") };
pub const Real: Symbol = unsafe { Symbol::unchecked_new("System`Real") };
pub const Repeated: Symbol = unsafe { Symbol::unchecked_new("System`Repeated") };
pub const RepeatedNull: Symbol = unsafe { Symbol::unchecked_new("System`RepeatedNull") };
pub const ReplaceAll: Symbol = unsafe { Symbol::unchecked_new("System`ReplaceAll") };
pub const ReplaceRepeated: Symbol = unsafe { Symbol::unchecked_new("System`ReplaceRepeated") };
pub const ReverseElement: Symbol = unsafe { Symbol::unchecked_new("System`ReverseElement") };
pub const ReverseEquilibrium: Symbol = unsafe { Symbol::unchecked_new("System`ReverseEquilibrium") };
pub const ReverseUpEquilibrium: Symbol = unsafe { Symbol::unchecked_new("System`ReverseUpEquilibrium") };
pub const RightArrow: Symbol = unsafe { Symbol::unchecked_new("System`RightArrow") };
pub const RightArrowBar: Symbol = unsafe { Symbol::unchecked_new("System`RightArrowBar") };
pub const RightArrowLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`RightArrowLeftArrow") };
pub const RightComposition: Symbol = unsafe { Symbol::unchecked_new("System`RightComposition") };
pub const RightDownTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`RightDownTeeVector") };
pub const RightDownVector: Symbol = unsafe { Symbol::unchecked_new("System`RightDownVector") };
pub const RightDownVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`RightDownVectorBar") };
pub const RightTee: Symbol = unsafe { Symbol::unchecked_new("System`RightTee") };
pub const RightTeeArrow: Symbol = unsafe { Symbol::unchecked_new("System`RightTeeArrow") };
pub const RightTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`RightTeeVector") };
pub const RightTriangle: Symbol = unsafe { Symbol::unchecked_new("System`RightTriangle") };
pub const RightTriangleBar: Symbol = unsafe { Symbol::unchecked_new("System`RightTriangleBar") };
pub const RightTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("System`RightTriangleEqual") };
pub const RightUpDownVector: Symbol = unsafe { Symbol::unchecked_new("System`RightUpDownVector") };
pub const RightUpTeeVector: Symbol = unsafe { Symbol::unchecked_new("System`RightUpTeeVector") };
pub const RightUpVector: Symbol = unsafe { Symbol::unchecked_new("System`RightUpVector") };
pub const RightUpVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`RightUpVectorBar") };
pub const RightVector: Symbol = unsafe { Symbol::unchecked_new("System`RightVector") };
pub const RightVectorBar: Symbol = unsafe { Symbol::unchecked_new("System`RightVectorBar") };
pub const RoundImplies: Symbol = unsafe { Symbol::unchecked_new("System`RoundImplies") };
pub const Rule: Symbol = unsafe { Symbol::unchecked_new("System`Rule") };
pub const RuleDelayed: Symbol = unsafe { Symbol::unchecked_new("System`RuleDelayed") };
pub const SameQ: Symbol = unsafe { Symbol::unchecked_new("System`SameQ") };
pub const Set: Symbol = unsafe { Symbol::unchecked_new("System`Set") };
pub const SetDelayed: Symbol = unsafe { Symbol::unchecked_new("System`SetDelayed") };
pub const ShortDownArrow: Symbol = unsafe { Symbol::unchecked_new("System`ShortDownArrow") };
pub const ShortLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`ShortLeftArrow") };
pub const ShortRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`ShortRightArrow") };
pub const ShortUpArrow: Symbol = unsafe { Symbol::unchecked_new("System`ShortUpArrow") };
pub const Slot: Symbol = unsafe { Symbol::unchecked_new("System`Slot") };
pub const SlotSequence: Symbol = unsafe { Symbol::unchecked_new("System`SlotSequence") };
pub const SmallCircle: Symbol = unsafe { Symbol::unchecked_new("System`SmallCircle") };
pub const Span: Symbol = unsafe { Symbol::unchecked_new("System`Span") };
pub const Sqrt: Symbol = unsafe { Symbol::unchecked_new("System`Sqrt") };
pub const Square: Symbol = unsafe { Symbol::unchecked_new("System`Square") };
pub const SquareIntersection: Symbol = unsafe { Symbol::unchecked_new("System`SquareIntersection") };
pub const SquareSubset: Symbol = unsafe { Symbol::unchecked_new("System`SquareSubset") };
pub const SquareSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("System`SquareSubsetEqual") };
pub const SquareSuperset: Symbol = unsafe { Symbol::unchecked_new("System`SquareSuperset") };
pub const SquareSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("System`SquareSupersetEqual") };
pub const SquareUnion: Symbol = unsafe { Symbol::unchecked_new("System`SquareUnion") };
pub const Star: Symbol = unsafe { Symbol::unchecked_new("System`Star") };
pub const String: Symbol = unsafe { Symbol::unchecked_new("System`String") };
pub const StringExpression: Symbol = unsafe { Symbol::unchecked_new("System`StringExpression") };
pub const StringJoin: Symbol = unsafe { Symbol::unchecked_new("System`StringJoin") };
pub const Subset: Symbol = unsafe { Symbol::unchecked_new("System`Subset") };
pub const SubsetEqual: Symbol = unsafe { Symbol::unchecked_new("System`SubsetEqual") };
pub const SubtractFrom: Symbol = unsafe { Symbol::unchecked_new("System`SubtractFrom") };
pub const Succeeds: Symbol = unsafe { Symbol::unchecked_new("System`Succeeds") };
pub const SucceedsEqual: Symbol = unsafe { Symbol::unchecked_new("System`SucceedsEqual") };
pub const SucceedsSlantEqual: Symbol = unsafe { Symbol::unchecked_new("System`SucceedsSlantEqual") };
pub const SucceedsTilde: Symbol = unsafe { Symbol::unchecked_new("System`SucceedsTilde") };
pub const SuchThat: Symbol = unsafe { Symbol::unchecked_new("System`SuchThat") };
pub const Sum: Symbol = unsafe { Symbol::unchecked_new("System`Sum") };
pub const Superset: Symbol = unsafe { Symbol::unchecked_new("System`Superset") };
pub const SupersetEqual: Symbol = unsafe { Symbol::unchecked_new("System`SupersetEqual") };
pub const Symbol: Symbol = unsafe { Symbol::unchecked_new("System`Symbol") };
pub const TagSet: Symbol = unsafe { Symbol::unchecked_new("System`TagSet") };
pub const TagSetDelayed: Symbol = unsafe { Symbol::unchecked_new("System`TagSetDelayed") };
pub const TagUnset: Symbol = unsafe { Symbol::unchecked_new("System`TagUnset") };
pub const TensorProduct: Symbol = unsafe { Symbol::unchecked_new("System`TensorProduct") };
pub const TensorWedge: Symbol = unsafe { Symbol::unchecked_new("System`TensorWedge") };
pub const Therefore: Symbol = unsafe { Symbol::unchecked_new("System`Therefore") };
pub const Tilde: Symbol = unsafe { Symbol::unchecked_new("System`Tilde") };
pub const TildeEqual: Symbol = unsafe { Symbol::unchecked_new("System`TildeEqual") };
pub const TildeFullEqual: Symbol = unsafe { Symbol::unchecked_new("System`TildeFullEqual") };
pub const TildeTilde: Symbol = unsafe { Symbol::unchecked_new("System`TildeTilde") };
pub const Times: Symbol = unsafe { Symbol::unchecked_new("System`Times") };
pub const TimesBy: Symbol = unsafe { Symbol::unchecked_new("System`TimesBy") };
pub const Transpose: Symbol = unsafe { Symbol::unchecked_new("System`Transpose") };
pub const TwoWayRule: Symbol = unsafe { Symbol::unchecked_new("System`TwoWayRule") };
pub const TypeSpecifier: Symbol = unsafe { Symbol::unchecked_new("System`TypeSpecifier") };
pub const UndirectedEdge: Symbol = unsafe { Symbol::unchecked_new("System`UndirectedEdge") };
pub const Union: Symbol = unsafe { Symbol::unchecked_new("System`Union") };
pub const UnionPlus: Symbol = unsafe { Symbol::unchecked_new("System`UnionPlus") };
pub const UnsameQ: Symbol = unsafe { Symbol::unchecked_new("System`UnsameQ") };
pub const Unset: Symbol = unsafe { Symbol::unchecked_new("System`Unset") };
pub const UpArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpArrow") };
pub const UpArrowBar: Symbol = unsafe { Symbol::unchecked_new("System`UpArrowBar") };
pub const UpArrowDownArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpArrowDownArrow") };
pub const UpDownArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpDownArrow") };
pub const UpEquilibrium: Symbol = unsafe { Symbol::unchecked_new("System`UpEquilibrium") };
pub const UpperLeftArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpperLeftArrow") };
pub const UpperRightArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpperRightArrow") };
pub const UpSet: Symbol = unsafe { Symbol::unchecked_new("System`UpSet") };
pub const UpSetDelayed: Symbol = unsafe { Symbol::unchecked_new("System`UpSetDelayed") };
pub const UpTee: Symbol = unsafe { Symbol::unchecked_new("System`UpTee") };
pub const UpTeeArrow: Symbol = unsafe { Symbol::unchecked_new("System`UpTeeArrow") };
pub const VectorGreater: Symbol = unsafe { Symbol::unchecked_new("System`VectorGreater") };
pub const VectorGreaterEqual: Symbol = unsafe { Symbol::unchecked_new("System`VectorGreaterEqual") };
pub const VectorLess: Symbol = unsafe { Symbol::unchecked_new("System`VectorLess") };
pub const VectorLessEqual: Symbol = unsafe { Symbol::unchecked_new("System`VectorLessEqual") };
pub const Vee: Symbol = unsafe { Symbol::unchecked_new("System`Vee") };
pub const VerticalBar: Symbol = unsafe { Symbol::unchecked_new("System`VerticalBar") };
pub const VerticalSeparator: Symbol = unsafe { Symbol::unchecked_new("System`VerticalSeparator") };
pub const VerticalTilde: Symbol = unsafe { Symbol::unchecked_new("System`VerticalTilde") };
pub const Wedge: Symbol = unsafe { Symbol::unchecked_new("System`Wedge") };
pub const Whitespace: Symbol = unsafe { Symbol::unchecked_new("System`Whitespace") };
pub const Xnor: Symbol = unsafe { Symbol::unchecked_new("System`Xnor") };
pub const Xor: Symbol = unsafe { Symbol::unchecked_new("System`Xor") };
pub const _Aborted: Symbol = unsafe { Symbol::unchecked_new("System`$Aborted") };

/// The name of each identifier in this module exactly matches a variant of the
/// [`TokenKind`][crate::tokenize::TokenKind] enum, which makes the
/// implementation of `token_to_symbol!` trivial.
pub mod Token {
    use crate::symbol::Symbol;

    pub const Amp: Symbol = unsafe { Symbol::unchecked_new("Token`Amp") };
    pub const AmpAmp: Symbol = unsafe { Symbol::unchecked_new("Token`AmpAmp") };
    pub const At: Symbol = unsafe { Symbol::unchecked_new("Token`At") };
    pub const AtAt: Symbol = unsafe { Symbol::unchecked_new("Token`AtAt") };
    pub const AtAtAt: Symbol = unsafe { Symbol::unchecked_new("Token`AtAtAt") };
    pub const AtStar: Symbol = unsafe { Symbol::unchecked_new("Token`AtStar") };
    pub const Bang: Symbol = unsafe { Symbol::unchecked_new("Token`Bang") };
    pub const BangBang: Symbol = unsafe { Symbol::unchecked_new("Token`BangBang") };
    pub const BangEqual: Symbol = unsafe { Symbol::unchecked_new("Token`BangEqual") };
    pub const Bar: Symbol = unsafe { Symbol::unchecked_new("Token`Bar") };
    pub const BarBar: Symbol = unsafe { Symbol::unchecked_new("Token`BarBar") };
    pub const BarGreater: Symbol = unsafe { Symbol::unchecked_new("Token`BarGreater") };
    pub const BarMinusGreater: Symbol = unsafe { Symbol::unchecked_new("Token`BarMinusGreater") };
    pub const Boxes_MultiSingleQuote: Symbol = unsafe { Symbol::unchecked_new("Token`Boxes`MultiSingleQuote") };
    pub const Boxes_MultiWhitespace: Symbol = unsafe { Symbol::unchecked_new("Token`Boxes`MultiWhitespace") };
    pub const Boxes_OpenParenStar: Symbol = unsafe { Symbol::unchecked_new("Token`Boxes`OpenParenStar") };
    pub const Boxes_StarCloseParen: Symbol = unsafe { Symbol::unchecked_new("Token`Boxes`StarCloseParen") };
    pub const Buffer1: Symbol = unsafe { Symbol::unchecked_new("Token`Buffer1") };
    pub const Buffer2: Symbol = unsafe { Symbol::unchecked_new("Token`Buffer2") };
    pub const Buffer3: Symbol = unsafe { Symbol::unchecked_new("Token`Buffer3") };
    pub const Buffer4: Symbol = unsafe { Symbol::unchecked_new("Token`Buffer4") };
    pub const Caret: Symbol = unsafe { Symbol::unchecked_new("Token`Caret") };
    pub const CaretColonEqual: Symbol = unsafe { Symbol::unchecked_new("Token`CaretColonEqual") };
    pub const CaretEqual: Symbol = unsafe { Symbol::unchecked_new("Token`CaretEqual") };
    pub const CloseCurly: Symbol = unsafe { Symbol::unchecked_new("Token`CloseCurly") };
    pub const CloseParen: Symbol = unsafe { Symbol::unchecked_new("Token`CloseParen") };
    pub const CloseSquare: Symbol = unsafe { Symbol::unchecked_new("Token`CloseSquare") };
    pub const Colon: Symbol = unsafe { Symbol::unchecked_new("Token`Colon") };
    pub const ColonColon: Symbol = unsafe { Symbol::unchecked_new("Token`ColonColon") };
    pub const ColonColonOpenSquare: Symbol = unsafe { Symbol::unchecked_new("Token`ColonColonOpenSquare") };
    pub const ColonEqual: Symbol = unsafe { Symbol::unchecked_new("Token`ColonEqual") };
    pub const ColonGreater: Symbol = unsafe { Symbol::unchecked_new("Token`ColonGreater") };
    pub const Comma: Symbol = unsafe { Symbol::unchecked_new("Token`Comma") };
    pub const Comment: Symbol = unsafe { Symbol::unchecked_new("Token`Comment") };
    pub const Count: Symbol = unsafe { Symbol::unchecked_new("Token`Count") };
    pub const Dot: Symbol = unsafe { Symbol::unchecked_new("Token`Dot") };
    pub const DotDot: Symbol = unsafe { Symbol::unchecked_new("Token`DotDot") };
    pub const DotDotDot: Symbol = unsafe { Symbol::unchecked_new("Token`DotDotDot") };
    pub const EndOfFile: Symbol = unsafe { Symbol::unchecked_new("Token`EndOfFile") };
    pub const Equal: Symbol = unsafe { Symbol::unchecked_new("Token`Equal") };
    pub const EqualBangEqual: Symbol = unsafe { Symbol::unchecked_new("Token`EqualBangEqual") };
    pub const EqualEqual: Symbol = unsafe { Symbol::unchecked_new("Token`EqualEqual") };
    pub const EqualEqualEqual: Symbol = unsafe { Symbol::unchecked_new("Token`EqualEqualEqual") };
    pub const Error_Aborted: Symbol = unsafe { Symbol::unchecked_new("Token`Error`Aborted") };
    pub const Error_ExpectedEqual: Symbol = unsafe { Symbol::unchecked_new("Token`Error`ExpectedEqual") };
    pub const Error_ExpectedFile: Symbol = unsafe { Symbol::unchecked_new("Token`Error`ExpectedFile") };
    pub const Error_ExpectedLetterlike: Symbol = unsafe { Symbol::unchecked_new("Token`Error`ExpectedLetterlike") };
    pub const Error_ExpectedOperand: Symbol = unsafe { Symbol::unchecked_new("Token`Error`ExpectedOperand") };
    pub const Error_ExpectedTag: Symbol = unsafe { Symbol::unchecked_new("Token`Error`ExpectedTag") };
    pub const Error_InfixImplicitNull: Symbol = unsafe { Symbol::unchecked_new("Token`Error`InfixImplicitNull") };
    pub const Error_Number: Symbol = unsafe { Symbol::unchecked_new("Token`Error`Number") };
    pub const Error_PrefixImplicitNull: Symbol = unsafe { Symbol::unchecked_new("Token`Error`PrefixImplicitNull") };
    pub const Error_UnexpectedCloser: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnexpectedCloser") };
    pub const Error_UnexpectedCommentCloser: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnexpectedCommentCloser") };
    pub const Error_UnhandledCharacter: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnhandledCharacter") };
    pub const Error_UnsafeCharacterEncoding: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnsafeCharacterEncoding") };
    pub const Error_UnsupportedToken: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnsupportedToken") };
    pub const Error_UnterminatedComment: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnterminatedComment") };
    pub const Error_UnterminatedFileString: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnterminatedFileString") };
    pub const Error_UnterminatedLinearSyntaxBlob: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnterminatedLinearSyntaxBlob") };
    pub const Error_UnterminatedString: Symbol = unsafe { Symbol::unchecked_new("Token`Error`UnterminatedString") };
    pub const Fake_ImplicitAll: Symbol = unsafe { Symbol::unchecked_new("Token`Fake`ImplicitAll") };
    pub const Fake_ImplicitNull: Symbol = unsafe { Symbol::unchecked_new("Token`Fake`ImplicitNull") };
    pub const Fake_ImplicitOne: Symbol = unsafe { Symbol::unchecked_new("Token`Fake`ImplicitOne") };
    pub const Fake_ImplicitTimes: Symbol = unsafe { Symbol::unchecked_new("Token`Fake`ImplicitTimes") };
    pub const Greater: Symbol = unsafe { Symbol::unchecked_new("Token`Greater") };
    pub const GreaterEqual: Symbol = unsafe { Symbol::unchecked_new("Token`GreaterEqual") };
    pub const GreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`GreaterGreater") };
    pub const GreaterGreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`GreaterGreaterGreater") };
    pub const Hash: Symbol = unsafe { Symbol::unchecked_new("Token`Hash") };
    pub const HashHash: Symbol = unsafe { Symbol::unchecked_new("Token`HashHash") };
    pub const Integer: Symbol = unsafe { Symbol::unchecked_new("Token`Integer") };
    pub const InternalNewline: Symbol = unsafe { Symbol::unchecked_new("Token`InternalNewline") };
    pub const Less: Symbol = unsafe { Symbol::unchecked_new("Token`Less") };
    pub const LessBar: Symbol = unsafe { Symbol::unchecked_new("Token`LessBar") };
    pub const LessEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LessEqual") };
    pub const LessGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LessGreater") };
    pub const LessLess: Symbol = unsafe { Symbol::unchecked_new("Token`LessLess") };
    pub const LessMinusGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LessMinusGreater") };
    pub const LinearSyntax_Amp: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Amp") };
    pub const LinearSyntax_At: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`At") };
    pub const LinearSyntax_BackTick: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`BackTick") };
    pub const LinearSyntax_Bang: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Bang") };
    pub const LinearSyntaxBlob: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntaxBlob") };
    pub const LinearSyntax_Caret: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Caret") };
    pub const LinearSyntax_CloseParen: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`CloseParen") };
    pub const LinearSyntax_Percent: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Percent") };
    pub const LinearSyntax_Plus: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Plus") };
    pub const LinearSyntax_Slash: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Slash") };
    pub const LinearSyntax_Space: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Space") };
    pub const LinearSyntax_Star: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Star") };
    pub const LinearSyntax_Under: Symbol = unsafe { Symbol::unchecked_new("Token`LinearSyntax`Under") };
    pub const LongName_And: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`And") };
    pub const LongName_Application: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Application") };
    pub const LongName_AutoLeftMatch: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`AutoLeftMatch") };
    pub const LongName_AutoRightMatch: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`AutoRightMatch") };
    pub const LongName_Backslash: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Backslash") };
    pub const LongName_Because: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Because") };
    pub const LongName_Cap: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Cap") };
    pub const LongName_CapitalDifferentialD: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CapitalDifferentialD") };
    pub const LongName_CenterDot: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CenterDot") };
    pub const LongName_CircleDot: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CircleDot") };
    pub const LongName_CircleMinus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CircleMinus") };
    pub const LongName_CirclePlus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CirclePlus") };
    pub const LongName_CircleTimes: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CircleTimes") };
    pub const LongName_ClockwiseContourIntegral: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ClockwiseContourIntegral") };
    pub const LongName_CloseCurlyDoubleQuote: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CloseCurlyDoubleQuote") };
    pub const LongName_CloseCurlyQuote: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CloseCurlyQuote") };
    pub const LongName_Colon: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Colon") };
    pub const LongName_Conditioned: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Conditioned") };
    pub const LongName_Congruent: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Congruent") };
    pub const LongName_Conjugate: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Conjugate") };
    pub const LongName_ConjugateTranspose: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ConjugateTranspose") };
    pub const LongName_ContinuedFractionK: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ContinuedFractionK") };
    pub const LongName_ContourIntegral: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ContourIntegral") };
    pub const LongName_Coproduct: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Coproduct") };
    pub const LongName_CounterClockwiseContourIntegral: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CounterClockwiseContourIntegral") };
    pub const LongName_Cross: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Cross") };
    pub const LongName_CubeRoot: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CubeRoot") };
    pub const LongName_Cup: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Cup") };
    pub const LongName_CupCap: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`CupCap") };
    pub const LongName_Del: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Del") };
    pub const LongName_Diamond: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Diamond") };
    pub const LongName_DifferenceDelta: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DifferenceDelta") };
    pub const LongName_DifferentialD: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DifferentialD") };
    pub const LongName_DirectedEdge: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DirectedEdge") };
    pub const LongName_DiscreteRatio: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DiscreteRatio") };
    pub const LongName_DiscreteShift: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DiscreteShift") };
    pub const LongName_Distributed: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Distributed") };
    pub const LongName_Divide: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Divide") };
    pub const LongName_Divides: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Divides") };
    pub const LongName_DivisionSlash: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DivisionSlash") };
    pub const LongName_DotEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DotEqual") };
    pub const LongName_DoubleContourIntegral: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleContourIntegral") };
    pub const LongName_DoubleDownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleDownArrow") };
    pub const LongName_DoubleLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLeftArrow") };
    pub const LongName_DoubleLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLeftRightArrow") };
    pub const LongName_DoubleLeftTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLeftTee") };
    pub const LongName_DoubleLongLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLongLeftArrow") };
    pub const LongName_DoubleLongLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLongLeftRightArrow") };
    pub const LongName_DoubleLongRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleLongRightArrow") };
    pub const LongName_DoubleRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleRightArrow") };
    pub const LongName_DoubleRightTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleRightTee") };
    pub const LongName_DoubleUpArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleUpArrow") };
    pub const LongName_DoubleUpDownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleUpDownArrow") };
    pub const LongName_DoubleVerticalBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DoubleVerticalBar") };
    pub const LongName_DownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownArrow") };
    pub const LongName_DownArrowBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownArrowBar") };
    pub const LongName_DownArrowUpArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownArrowUpArrow") };
    pub const LongName_DownLeftRightVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownLeftRightVector") };
    pub const LongName_DownLeftTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownLeftTeeVector") };
    pub const LongName_DownLeftVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownLeftVector") };
    pub const LongName_DownLeftVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownLeftVectorBar") };
    pub const LongName_DownRightTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownRightTeeVector") };
    pub const LongName_DownRightVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownRightVector") };
    pub const LongName_DownRightVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownRightVectorBar") };
    pub const LongName_DownTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownTee") };
    pub const LongName_DownTeeArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`DownTeeArrow") };
    pub const LongName_Element: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Element") };
    pub const LongName_Equal: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Equal") };
    pub const LongName_EqualTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`EqualTilde") };
    pub const LongName_Equilibrium: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Equilibrium") };
    pub const LongName_Equivalent: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Equivalent") };
    pub const LongName_Exists: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Exists") };
    pub const LongName_ExpectationE: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ExpectationE") };
    pub const LongName_ForAll: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ForAll") };
    pub const LongName_Function: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Function") };
    pub const LongName_GreaterEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterEqual") };
    pub const LongName_GreaterEqualLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterEqualLess") };
    pub const LongName_GreaterFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterFullEqual") };
    pub const LongName_GreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterGreater") };
    pub const LongName_GreaterLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterLess") };
    pub const LongName_GreaterSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterSlantEqual") };
    pub const LongName_GreaterTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`GreaterTilde") };
    pub const LongName_HermitianConjugate: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`HermitianConjugate") };
    pub const LongName_HumpDownHump: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`HumpDownHump") };
    pub const LongName_HumpEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`HumpEqual") };
    pub const LongName_ImplicitPlus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ImplicitPlus") };
    pub const LongName_Implies: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Implies") };
    pub const LongName_Integral: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Integral") };
    pub const LongName_Intersection: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Intersection") };
    pub const LongName_InvisibleApplication: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`InvisibleApplication") };
    pub const LongName_InvisibleComma: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`InvisibleComma") };
    pub const LongName_InvisiblePostfixScriptBase: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`InvisiblePostfixScriptBase") };
    pub const LongName_InvisiblePrefixScriptBase: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`InvisiblePrefixScriptBase") };
    pub const LongName_InvisibleTimes: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`InvisibleTimes") };
    pub const LongName_LeftAngleBracket: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftAngleBracket") };
    pub const LongName_LeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftArrow") };
    pub const LongName_LeftArrowBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftArrowBar") };
    pub const LongName_LeftArrowRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftArrowRightArrow") };
    pub const LongName_LeftAssociation: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftAssociation") };
    pub const LongName_LeftBracketingBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftBracketingBar") };
    pub const LongName_LeftCeiling: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftCeiling") };
    pub const LongName_LeftDoubleBracket: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftDoubleBracket") };
    pub const LongName_LeftDoubleBracketingBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftDoubleBracketingBar") };
    pub const LongName_LeftDownTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftDownTeeVector") };
    pub const LongName_LeftDownVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftDownVector") };
    pub const LongName_LeftDownVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftDownVectorBar") };
    pub const LongName_LeftFloor: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftFloor") };
    pub const LongName_LeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftRightArrow") };
    pub const LongName_LeftRightVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftRightVector") };
    pub const LongName_LeftTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTee") };
    pub const LongName_LeftTeeArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTeeArrow") };
    pub const LongName_LeftTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTeeVector") };
    pub const LongName_LeftTriangle: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTriangle") };
    pub const LongName_LeftTriangleBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTriangleBar") };
    pub const LongName_LeftTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftTriangleEqual") };
    pub const LongName_LeftUpDownVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftUpDownVector") };
    pub const LongName_LeftUpTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftUpTeeVector") };
    pub const LongName_LeftUpVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftUpVector") };
    pub const LongName_LeftUpVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftUpVectorBar") };
    pub const LongName_LeftVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftVector") };
    pub const LongName_LeftVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LeftVectorBar") };
    pub const LongName_LessEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessEqual") };
    pub const LongName_LessEqualGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessEqualGreater") };
    pub const LongName_LessFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessFullEqual") };
    pub const LongName_LessGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessGreater") };
    pub const LongName_LessLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessLess") };
    pub const LongName_LessSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessSlantEqual") };
    pub const LongName_LessTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LessTilde") };
    pub const LongName_Limit: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Limit") };
    pub const LongName_LongEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LongEqual") };
    pub const LongName_LongLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LongLeftArrow") };
    pub const LongName_LongLeftRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LongLeftRightArrow") };
    pub const LongName_LongRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LongRightArrow") };
    pub const LongName_LowerLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LowerLeftArrow") };
    pub const LongName_LowerRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`LowerRightArrow") };
    pub const LongName_MaxLimit: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`MaxLimit") };
    pub const LongName_MinLimit: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`MinLimit") };
    pub const LongName_Minus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Minus") };
    pub const LongName_MinusPlus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`MinusPlus") };
    pub const LongName_Nand: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Nand") };
    pub const LongName_NestedGreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NestedGreaterGreater") };
    pub const LongName_NestedLessLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NestedLessLess") };
    pub const LongName_Nor: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Nor") };
    pub const LongName_Not: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Not") };
    pub const LongName_NotCongruent: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotCongruent") };
    pub const LongName_NotCupCap: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotCupCap") };
    pub const LongName_NotDoubleVerticalBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotDoubleVerticalBar") };
    pub const LongName_NotElement: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotElement") };
    pub const LongName_NotEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotEqual") };
    pub const LongName_NotEqualTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotEqualTilde") };
    pub const LongName_NotExists: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotExists") };
    pub const LongName_NotGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreater") };
    pub const LongName_NotGreaterEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterEqual") };
    pub const LongName_NotGreaterFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterFullEqual") };
    pub const LongName_NotGreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterGreater") };
    pub const LongName_NotGreaterLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterLess") };
    pub const LongName_NotGreaterSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterSlantEqual") };
    pub const LongName_NotGreaterTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotGreaterTilde") };
    pub const LongName_NotHumpDownHump: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotHumpDownHump") };
    pub const LongName_NotHumpEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotHumpEqual") };
    pub const LongName_NotLeftTriangle: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLeftTriangle") };
    pub const LongName_NotLeftTriangleBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLeftTriangleBar") };
    pub const LongName_NotLeftTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLeftTriangleEqual") };
    pub const LongName_NotLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLess") };
    pub const LongName_NotLessEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessEqual") };
    pub const LongName_NotLessFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessFullEqual") };
    pub const LongName_NotLessGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessGreater") };
    pub const LongName_NotLessLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessLess") };
    pub const LongName_NotLessSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessSlantEqual") };
    pub const LongName_NotLessTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotLessTilde") };
    pub const LongName_NotNestedGreaterGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotNestedGreaterGreater") };
    pub const LongName_NotNestedLessLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotNestedLessLess") };
    pub const LongName_NotPrecedes: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotPrecedes") };
    pub const LongName_NotPrecedesEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotPrecedesEqual") };
    pub const LongName_NotPrecedesSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotPrecedesSlantEqual") };
    pub const LongName_NotPrecedesTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotPrecedesTilde") };
    pub const LongName_NotReverseElement: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotReverseElement") };
    pub const LongName_NotRightTriangle: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotRightTriangle") };
    pub const LongName_NotRightTriangleBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotRightTriangleBar") };
    pub const LongName_NotRightTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotRightTriangleEqual") };
    pub const LongName_NotSquareSubset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSquareSubset") };
    pub const LongName_NotSquareSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSquareSubsetEqual") };
    pub const LongName_NotSquareSuperset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSquareSuperset") };
    pub const LongName_NotSquareSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSquareSupersetEqual") };
    pub const LongName_NotSubset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSubset") };
    pub const LongName_NotSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSubsetEqual") };
    pub const LongName_NotSucceeds: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSucceeds") };
    pub const LongName_NotSucceedsEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSucceedsEqual") };
    pub const LongName_NotSucceedsSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSucceedsSlantEqual") };
    pub const LongName_NotSucceedsTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSucceedsTilde") };
    pub const LongName_NotSuperset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSuperset") };
    pub const LongName_NotSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotSupersetEqual") };
    pub const LongName_NotTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotTilde") };
    pub const LongName_NotTildeEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotTildeEqual") };
    pub const LongName_NotTildeFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotTildeFullEqual") };
    pub const LongName_NotTildeTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotTildeTilde") };
    pub const LongName_NotVerticalBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`NotVerticalBar") };
    pub const LongName_OpenCurlyDoubleQuote: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`OpenCurlyDoubleQuote") };
    pub const LongName_OpenCurlyQuote: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`OpenCurlyQuote") };
    pub const LongName_Or: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Or") };
    pub const LongName_PartialD: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PartialD") };
    pub const LongName_PermutationProduct: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PermutationProduct") };
    pub const LongName_Perpendicular: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Perpendicular") };
    pub const LongName_Piecewise: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Piecewise") };
    pub const LongName_PlusMinus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PlusMinus") };
    pub const LongName_Precedes: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Precedes") };
    pub const LongName_PrecedesEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PrecedesEqual") };
    pub const LongName_PrecedesSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PrecedesSlantEqual") };
    pub const LongName_PrecedesTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`PrecedesTilde") };
    pub const LongName_ProbabilityPr: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ProbabilityPr") };
    pub const LongName_Product: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Product") };
    pub const LongName_Proportion: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Proportion") };
    pub const LongName_Proportional: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Proportional") };
    pub const LongName_ReverseElement: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ReverseElement") };
    pub const LongName_ReverseEquilibrium: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ReverseEquilibrium") };
    pub const LongName_ReverseUpEquilibrium: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ReverseUpEquilibrium") };
    pub const LongName_RightAngleBracket: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightAngleBracket") };
    pub const LongName_RightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightArrow") };
    pub const LongName_RightArrowBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightArrowBar") };
    pub const LongName_RightArrowLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightArrowLeftArrow") };
    pub const LongName_RightAssociation: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightAssociation") };
    pub const LongName_RightBracketingBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightBracketingBar") };
    pub const LongName_RightCeiling: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightCeiling") };
    pub const LongName_RightDoubleBracket: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightDoubleBracket") };
    pub const LongName_RightDoubleBracketingBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightDoubleBracketingBar") };
    pub const LongName_RightDownTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightDownTeeVector") };
    pub const LongName_RightDownVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightDownVector") };
    pub const LongName_RightDownVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightDownVectorBar") };
    pub const LongName_RightFloor: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightFloor") };
    pub const LongName_RightTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTee") };
    pub const LongName_RightTeeArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTeeArrow") };
    pub const LongName_RightTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTeeVector") };
    pub const LongName_RightTriangle: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTriangle") };
    pub const LongName_RightTriangleBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTriangleBar") };
    pub const LongName_RightTriangleEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightTriangleEqual") };
    pub const LongName_RightUpDownVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightUpDownVector") };
    pub const LongName_RightUpTeeVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightUpTeeVector") };
    pub const LongName_RightUpVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightUpVector") };
    pub const LongName_RightUpVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightUpVectorBar") };
    pub const LongName_RightVector: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightVector") };
    pub const LongName_RightVectorBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RightVectorBar") };
    pub const LongName_RoundImplies: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RoundImplies") };
    pub const LongName_Rule: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Rule") };
    pub const LongName_RuleDelayed: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`RuleDelayed") };
    pub const LongName_ShortDownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ShortDownArrow") };
    pub const LongName_ShortLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ShortLeftArrow") };
    pub const LongName_ShortRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ShortRightArrow") };
    pub const LongName_ShortUpArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`ShortUpArrow") };
    pub const LongName_SmallCircle: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SmallCircle") };
    pub const LongName_Sqrt: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Sqrt") };
    pub const LongName_Square: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Square") };
    pub const LongName_SquareIntersection: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareIntersection") };
    pub const LongName_SquareSubset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareSubset") };
    pub const LongName_SquareSubsetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareSubsetEqual") };
    pub const LongName_SquareSuperset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareSuperset") };
    pub const LongName_SquareSupersetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareSupersetEqual") };
    pub const LongName_SquareUnion: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SquareUnion") };
    pub const LongName_Star: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Star") };
    pub const LongName_Subset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Subset") };
    pub const LongName_SubsetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SubsetEqual") };
    pub const LongName_Succeeds: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Succeeds") };
    pub const LongName_SucceedsEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SucceedsEqual") };
    pub const LongName_SucceedsSlantEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SucceedsSlantEqual") };
    pub const LongName_SucceedsTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SucceedsTilde") };
    pub const LongName_SuchThat: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SuchThat") };
    pub const LongName_Sum: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Sum") };
    pub const LongName_Superset: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Superset") };
    pub const LongName_SupersetEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`SupersetEqual") };
    pub const LongName_TensorProduct: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TensorProduct") };
    pub const LongName_TensorWedge: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TensorWedge") };
    pub const LongName_Therefore: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Therefore") };
    pub const LongName_Tilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Tilde") };
    pub const LongName_TildeEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TildeEqual") };
    pub const LongName_TildeFullEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TildeFullEqual") };
    pub const LongName_TildeTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TildeTilde") };
    pub const LongName_Times: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Times") };
    pub const LongName_Transpose: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Transpose") };
    pub const LongName_TwoWayRule: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`TwoWayRule") };
    pub const LongName_UndirectedEdge: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UndirectedEdge") };
    pub const LongName_Union: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Union") };
    pub const LongName_UnionPlus: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UnionPlus") };
    pub const LongName_UpArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpArrow") };
    pub const LongName_UpArrowBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpArrowBar") };
    pub const LongName_UpArrowDownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpArrowDownArrow") };
    pub const LongName_UpDownArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpDownArrow") };
    pub const LongName_UpEquilibrium: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpEquilibrium") };
    pub const LongName_UpperLeftArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpperLeftArrow") };
    pub const LongName_UpperRightArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpperRightArrow") };
    pub const LongName_UpTee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpTee") };
    pub const LongName_UpTeeArrow: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`UpTeeArrow") };
    pub const LongName_VectorGreater: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VectorGreater") };
    pub const LongName_VectorGreaterEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VectorGreaterEqual") };
    pub const LongName_VectorLess: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VectorLess") };
    pub const LongName_VectorLessEqual: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VectorLessEqual") };
    pub const LongName_Vee: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Vee") };
    pub const LongName_VerticalBar: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VerticalBar") };
    pub const LongName_VerticalSeparator: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VerticalSeparator") };
    pub const LongName_VerticalTilde: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`VerticalTilde") };
    pub const LongName_Wedge: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Wedge") };
    pub const LongName_Xnor: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Xnor") };
    pub const LongName_Xor: Symbol = unsafe { Symbol::unchecked_new("Token`LongName`Xor") };
    pub const Minus: Symbol = unsafe { Symbol::unchecked_new("Token`Minus") };
    pub const MinusEqual: Symbol = unsafe { Symbol::unchecked_new("Token`MinusEqual") };
    pub const MinusGreater: Symbol = unsafe { Symbol::unchecked_new("Token`MinusGreater") };
    pub const MinusMinus: Symbol = unsafe { Symbol::unchecked_new("Token`MinusMinus") };
    pub const Newline: Symbol = unsafe { Symbol::unchecked_new("Token`Newline") };
    pub const OpenCurly: Symbol = unsafe { Symbol::unchecked_new("Token`OpenCurly") };
    pub const OpenParen: Symbol = unsafe { Symbol::unchecked_new("Token`OpenParen") };
    pub const OpenSquare: Symbol = unsafe { Symbol::unchecked_new("Token`OpenSquare") };
    pub const Percent: Symbol = unsafe { Symbol::unchecked_new("Token`Percent") };
    pub const PercentPercent: Symbol = unsafe { Symbol::unchecked_new("Token`PercentPercent") };
    pub const Plus: Symbol = unsafe { Symbol::unchecked_new("Token`Plus") };
    pub const PlusEqual: Symbol = unsafe { Symbol::unchecked_new("Token`PlusEqual") };
    pub const PlusPlus: Symbol = unsafe { Symbol::unchecked_new("Token`PlusPlus") };
    pub const Question: Symbol = unsafe { Symbol::unchecked_new("Token`Question") };
    pub const QuestionQuestion: Symbol = unsafe { Symbol::unchecked_new("Token`QuestionQuestion") };
    pub const Rational: Symbol = unsafe { Symbol::unchecked_new("Token`Rational") };
    pub const Real: Symbol = unsafe { Symbol::unchecked_new("Token`Real") };
    pub const Semi: Symbol = unsafe { Symbol::unchecked_new("Token`Semi") };
    pub const SemiSemi: Symbol = unsafe { Symbol::unchecked_new("Token`SemiSemi") };
    pub const SingleQuote: Symbol = unsafe { Symbol::unchecked_new("Token`SingleQuote") };
    pub const Slash: Symbol = unsafe { Symbol::unchecked_new("Token`Slash") };
    pub const SlashAt: Symbol = unsafe { Symbol::unchecked_new("Token`SlashAt") };
    pub const SlashColon: Symbol = unsafe { Symbol::unchecked_new("Token`SlashColon") };
    pub const SlashDot: Symbol = unsafe { Symbol::unchecked_new("Token`SlashDot") };
    pub const SlashEqual: Symbol = unsafe { Symbol::unchecked_new("Token`SlashEqual") };
    pub const SlashSemi: Symbol = unsafe { Symbol::unchecked_new("Token`SlashSemi") };
    pub const SlashSlash: Symbol = unsafe { Symbol::unchecked_new("Token`SlashSlash") };
    pub const SlashSlashAt: Symbol = unsafe { Symbol::unchecked_new("Token`SlashSlashAt") };
    pub const SlashSlashDot: Symbol = unsafe { Symbol::unchecked_new("Token`SlashSlashDot") };
    pub const SlashSlashEqual: Symbol = unsafe { Symbol::unchecked_new("Token`SlashSlashEqual") };
    pub const SlashStar: Symbol = unsafe { Symbol::unchecked_new("Token`SlashStar") };
    pub const Star: Symbol = unsafe { Symbol::unchecked_new("Token`Star") };
    pub const StarEqual: Symbol = unsafe { Symbol::unchecked_new("Token`StarEqual") };
    pub const StarStar: Symbol = unsafe { Symbol::unchecked_new("Token`StarStar") };
    pub const String: Symbol = unsafe { Symbol::unchecked_new("Token`String") };
    pub const Symbol: Symbol = unsafe { Symbol::unchecked_new("Token`Symbol") };
    pub const Tilde: Symbol = unsafe { Symbol::unchecked_new("Token`Tilde") };
    pub const TildeTilde: Symbol = unsafe { Symbol::unchecked_new("Token`TildeTilde") };
    pub const ToplevelNewline: Symbol = unsafe { Symbol::unchecked_new("Token`ToplevelNewline") };
    pub const Under: Symbol = unsafe { Symbol::unchecked_new("Token`Under") };
    pub const UnderDot: Symbol = unsafe { Symbol::unchecked_new("Token`UnderDot") };
    pub const UnderUnder: Symbol = unsafe { Symbol::unchecked_new("Token`UnderUnder") };
    pub const UnderUnderUnder: Symbol = unsafe { Symbol::unchecked_new("Token`UnderUnderUnder") };
    pub const Unknown: Symbol = unsafe { Symbol::unchecked_new("Token`Unknown") };
    pub const Whitespace: Symbol = unsafe { Symbol::unchecked_new("Token`Whitespace") };
}
